config/routes.rb
Thirtyone::Application.routes.draw do

  resources :local_resource_categories

  resources :local_resources do
    collection do
      get :search
    end
  end

  resources :visits

  resources :user_roles

  devise_for :users

  resources :calendar, only: [:index]

  scope 'inventory' do
    resources :items, as: 'inventory_items', controller: 'inventory_items'
    resources :orders, controller: 'inventory_orders'

    resources :inventory_stock_records
  end

  root  'static_pages#index'

  resources :user, controller: 'users', only: [:index, :edit, :update]
  resources :role, as: "roles", controller: "roles", via: :all

  match '/adminsetup', :controller => 'adminsetup', :action => 'setup', :via => 'get'
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_new', via: :get
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_create', via: :post

  resources :event, as: 'events', controller: 'event', via: :all

  resources :households, controller: 'household' do
    collection do
      get :search
      get :select
      get '/:id/merge'            => 'household#merge_select',        as: 'merge_select'
      get '/:id/merge/:merge_id'  => 'household#merge_select_fields', as: 'merge_select_fields'
      patch ':id/merge/:merge_id' => 'household#merge',               as: 'merge'
    end
    resources :addresses
  end

  resources :event, as: "events", controller: "event", via: :all

  resources :work_schedule, as: "work_schedules", controller: "work_schedule", via: :all

  resources :people do
    collection do
      get 'search'
    end
  end

  delete '/user/:id/email_change'     => 'users#cancel_pending_email_change', as: 'cancel_pending_email_change'
  post '/user/:id/email_confirmation' => 'users#send_confirmation_email', as: 'send_confirmation_email'
  get '/user/:id/email_confirmation'  => 'users#confirm_email_change', as: 'confirm_email_change'

  match '/people/new', :controller => 'people', :action => 'new', via: :post

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index

  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_topnav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "ThirtyOne", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#">Menu</a>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="left">
        <li class="divider"></li>
        <li class="<%= "active" if current_page?(people_path) %>"><a href="<%= people_path %>">Start Serving</a></li>
        <li class="divider"></li>
        <li class="<%= "active" if current_page?(households_path) %>"><a href="<%= households_path %>">Households</a></li>
        <li class="divider"></li>
        <li class="<%= "active" if current_page?(calendar_index_path) %>"><a href="<%= calendar_index_path %>">Scheduling</a></li>
        <li class="divider"></li>
        <li class="<%= "active" if current_page?(inventory_items_path) %>"><a href="<%= inventory_items_path %>">Inventory</a></li>
        <li class="divider"></li>
        <li><a href="#">Reports</a></li>
        <li class="divider"></li>
        <li class="<%= 'active' if current_page?(user_index_path) %>"><a href="<%= user_index_path %>">Users</a></li>
        <li class="divider"></li>
        <li class="<%= 'active' if current_page?(local_resources_path) %>"><%= link_to 'Local Resources', local_resources_path %></li>
        <li class="divider"></li>
        <% if current_user.has_access?(PERM_ADMIN) %>
          <li class="has-dropdown">
            <a href="#">Admin</a>
              <ul class="dropdown">
                <li class="<%= 'active' if current_page?(roles_path) %>"><a href="<%= roles_path %>">Manage Roles</a></li>
                <li class="<%= 'active' if current_page?(roles_bulk_path) %>"><a href="<%= roles_bulk_path %>">Bulk Assign Roles</a></li>
                <li class="<%= 'active' if current_page?(local_resource_categories_path) %>"><%= link_to 'Manage Local Resource Categories', local_resource_categories_path %></li>
              </ul>
          </li>
        <% end %>
    </ul>
    <ul class="right">
        <li class="divider"></li>
        <% if current_user.person %>
          <li><a href="<%= edit_user_path(current_user.id) %>">My Account</a></li>
        <% end %>
        <li class="divider"></li>
        <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
    </ul>
  </section>
</nav>

app/views/static_pages/_unauthTopnav.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "ThirtyOne", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon">
      <a href="#">Menu</a>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
        <li class="divider"></li>
        <li><a href="<%= new_user_session_path %>">Login</a></li>
    </ul>
  </section>
</nav>

app/views/static_pages/index.html.erb
<div style="margin-top:20px;" class="row">
    <div class="small-12 medium-10 large-8 columns small-centered">
        <h3>ThirtyOne - A Food Pantry App</h3>
        <blockquote>
            Therefore do not be anxious, saying, 'What shall we eat?' or 'What shall we drink?' or 'What shall we wear?'.  For the Gentiles seek after all these things, and your heavenly Father knows that you need them all. But seek first the kingdom of God and his righteousness, and all these things will be added to you.</br>
            <span class="right">Matthew 6:31-33</span>
        </blockquote>
        <div style="padding-top:10px">
           <a class="button small" href="<%= people_path %>">Start Serving</a>
        </div>
     </div>
</div>