config/routes.rb
Thirtyone::Application.routes.draw do

  resources :local_resource_categories

  resources :local_resources do
    collection do
      get :search
    end
  end

  resources :visits

  resources :user_roles

  devise_for :users

  resources :calendar, only: [:index]

  scope 'inventory' do
    resources :items, as: 'inventory_items', controller: 'inventory_items'
    resources :orders, controller: 'inventory_orders'

    resources :inventory_stock_records
  end

  root  'static_pages#index'

  resources :user, controller: 'users', only: [:index, :edit, :update]
  resources :role, as: "roles", controller: "roles", via: :all

  match '/adminsetup', :controller => 'adminsetup', :action => 'setup', :via => 'get'
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_new', via: :get
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_create', via: :post

  resources :event, as: 'events', controller: 'event', via: :all

  resources :households, controller: 'household' do
    collection do
      get :search
      get :select
      get '/:id/merge'            => 'household#merge_select',        as: 'merge_select'
      get '/:id/merge/:merge_id'  => 'household#merge_select_fields', as: 'merge_select_fields'
      patch ':id/merge/:merge_id' => 'household#merge',               as: 'merge'
    end
    resources :addresses
  end

  resources :event, as: "events", controller: "event", via: :all

  resources :work_schedule, as: "work_schedules", controller: "work_schedule", via: :all

  resources :people do
    collection do
      get 'search'
    end
  end

  delete '/user/:id/email_change'     => 'users#cancel_pending_email_change', as: 'cancel_pending_email_change'
  post '/user/:id/email_confirmation' => 'users#send_confirmation_email', as: 'send_confirmation_email'
  get '/user/:id/email_confirmation'  => 'users#confirm_email_change', as: 'confirm_email_change'

  match '/people/new', :controller => 'people', :action => 'new', via: :post

end

app/models/person.rb
# == Schema Information
#
# Table name: people
#
#  id           :integer          not null, primary key
#  firstname    :string
#  lastname     :string
#  phone        :string
#  phone_ext    :string
#  created_at   :datetime
#  updated_at   :datetime
#  household_id :integer
#  email        :string
#

class Person < ActiveRecord::Base
  include PhoneMethod

  acts_as_paranoid
#  has_notes
  has_and_belongs_to_many :notes
  belongs_to :household, autosave: true
  has_one :user, autosave: true
  accepts_nested_attributes_for :notes, :allow_destroy => true
  validates_presence_of :firstname, :lastname, :household
  validates_associated :household, :notes
  validate :custom_validate
  before_save :strip_phone_number

  def fullname
    if lastname
      "#{firstname} #{lastname}"
    else
      firstname
    end
  end

  def formal_name
    fn = lastname || ''
    fn += ', ' if fn and firstname and fn.length > 0 and firstname.length > 0
    fn += firstname if firstname and firstname.length > 0
    fn
  end

  def add_custom_error(attribute, message)
    if @custom_errors.nil?
      @custom_errors = {}
    end
    @custom_errors[attribute] = message
  end

  def custom_validate
    unless @custom_errors.nil?
      @custom_errors.each do |k, v|
        errors.add(k.to_sym, v)
      end
    end
  end

  def strip_phone_number
    self.phone = self.strip_phone(self.phone)
    self.phone_ext = self.strip_phone_ext(self.phone_ext)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :init
  before_action :authorize_person

  def init
    @errors = []
  end

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
    @new_person = Person.new
    @all_states = State.all
  end

  # GET /people/search
  # GET /people/search.json
  def search
    @people = PeopleSearch.search(params)
    respond_to do |format|
      format.html {
        if params[:ajax]
          render partial: 'search_results'
        else
          @new_person = Person.new
          @search_string = params[:search] ? params[:search].join(' ') : ''
          render action: 'index'
        end
      }
      format.json { render action: 'index.json' }
    end
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @household = @person.household
  end

  # GET /people/new
  def new
    @person = Person.new
    @all_states = State.all
    @new_household = Household.new
    if params[:search]
      @person.firstname, @person.lastname = params[:search].split(' ', 2)
    end

    if params[:household_id]
      @person.household = Household.find_by(id: params[:household_id])
    elsif params[:household_data]
      household_data = JSON.load(params[:household_data])
      address_data = household_data['address']
      @new_household.address = Address.new(address_data)
    end

    @person.household ||= @new_household
  end

  # GET /people/1/edit
  def edit
    @household = @person.household
    @all_states = State.all
    @is_user = !@person.user.nil?
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new
    manage_create_or_update
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    manage_create_or_update(true)
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def redirect_to_url
    if params[:redirect_to_url]
      return params[:redirect_to_url]
    end
  end

  helper_method :redirect_to_url

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find_by(id: params[:id])
    @all_states = State.all
    redirect_to action: 'index' unless @person
  end

  def authorize_person
    @person ? (authorize @person) : (authorize :person)
  end

  def manage_create_or_update(is_update = false)
    @person ||= Person.new
    psv = PeopleSubmissionValidator.new(params)

    respond_to do |format|
      if psv.process(@person)
        @person.user.send_new_account_instructions unless(@person.user.nil? || is_update)

        url = edit_user_path(@person.user) if params[:create_user] == 'yes'

        # Redirect to the person, unless we're creating a new household
        is_update ? url ||= params[:redirect_to_url] || @person : url ||= @person.household

        msg = is_update ? "updated" : "created"

        format.html { redirect_to url, notice: "Person was successfully #{msg}." }
        if is_update
          format.json { head :no_content }
        else
          format.json { render action: 'show', status: :created, location: @person }
        end
      else
        format.html { render action: is_update ? 'edit' : 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person, :html => {:name => 'new_person'}) do |f| %>
    <% if @is_user %>
        <h5>Want to edit user attributes? Go to the <a href="<%= edit_user_url(@person.user) %>">edit user</a> page.</h5>
    <% end %>
    <% if @person.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

          <ul>
            <% @person.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div style="color: red;">* denotes required field</div>
    <div class="field">
      <label class="required" for="person_firstname">First Name</label>
      <%= f.text_field :firstname, :required => true %>
    </div>
    <div class="field">
      <label class="required" for="person_lastname">Last Name</label>
      <%= f.text_field :lastname, :required => true %>
    </div>
    <div class="field">
      <%= f.label :email %>
      <% if @is_user %>
          User e-mail must be edited from the <a href="<%= edit_user_path(@person.user) %>">edit user</a> page.
      <% end %>
      <%= f.email_field :email, :disabled => @is_user %>
    </div>
    <div class="phone_field">
      <div class="phone_left">
        <span><%= f.label :phone %></span>
        <span><%= f.text_field :phone %></span>
      </div>
      <div class="phone_right">
        <span><%= f.label :phone_ext %></span>
        <span><%= f.text_field :phone_ext %></span>
      </div>
    </div>
    <h3>Household</h3>
    <div id="selectHouseholdModal" class="reveal-modal" data-reveal>
      <a class="close-reveal-modal">&#215;</a>
    </div>

    <div class="field">
      <div id="select_household_message" class="field <%= 'hide' if @person.household %>">
        You must select a household to associate this person with. If this is the first visit from a household, you can create a new one.<br/>
      </div>
      <button type="button" id="select_or_create_household_button" onclick="$('#selectHouseholdModal')
          .foundation('reveal',
          'open',
          {url: '<%= select_households_url  %>',
              data: {ajax: true},
              complete: function(xhr, status) {
                  $('#selectHouseholdModal')
                      .append('<a class=\'close-reveal-modal\'>&#215;</a>');

            } });" class="medium button" >Select or Create Household</button>
      </div>
    <div id="household_div" class="row">
      <%=
        if @person.household
          @household = @person.household
          if @person.household.new_record?
            render 'household/new'
          else
            render 'household/show'
          end
        end
      %>
    </div>
    <h3>Allow User to Login</h3>
    <div>Do you want to allow this user to login as a volunteer?
      <%= radio_button_tag(:create_user, :yes, (!!@person.user || params[:create_user] == 'yes')) %><label for="create_user_yes">Yes</label>
      <%= radio_button_tag(:create_user, :no, (!@person.user && params[:create_user] != 'yes')) %><label for="create_user_no">No</label>
    </div>
    <% if redirect_to_url %>
        <input type="hidden" name="redirect_to_url" value="<%= redirect_to_url %>"/>
    <% end %>

    <h3>Notes</h3>
    <% @person.notes.each do |n| %>
        <div class="row note">
          <div class="small-12 columns">
            <%= f.fields_for :notes, n do |nf| %>
                <%= nf.collection_select :note_type_id, NoteType.all, :id, :name %>
                <%= nf.text_area :note %>
                <%= nf.check_box :_destroy, class: "delete-note-checkbox" %>
                <%= nf.label :_destroy, "Delete Note" %>
            <% end %>
          </div>
        </div>
    <% end %>

    <h4>New Note</h4>
    <div class="row space-above space-bottom">
      <div class="small-12 columns new-note">
        <%= f.fields_for :notes, @person.notes.build do |nf| %>
            <%= nf.collection_select :note_type_id, NoteType.all, :id, :name %>
            <%= nf.text_area :note %>
        <% end %>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <div class="field left">
          <%= f.submit class: 'medium button' %>
        </div>
        <div class="right">
          <button class="medium button" onclick="window.location='<%= redirect_to_url ? redirect_to_url : people_url %>';">
            Cancel
          </button>
        </div>
      </div>
    </div>

<% end %>
<script>
  var validator = new FormValidator('new_person', [{
    name: 'person[firstname]',
    display: 'First Name',
    rules: 'required'
  }, {
    name: 'person[lastname]',
    display: 'Last Name',
    rules: 'required'
  }], function (errors, event) {
    if (errors.length > 0) {
      event.preventDefault();
      var errorString = '';

      for (var i = 0, errorLength = errors.length; i < errorLength; i++) {
        errorString += errors[i].message + '<br />';
        var thisInput = $('input[name="' + errors[i].name + '"]')
        var thisId = $(thisInput).attr('id');
        $(thisInput).addClass('error');
        $('label[for="' + thisId + '"]').addClass('error');
      }
      $('#new_person').prepend('<div class="alert-box alert" id="new_person_box">' + errorString + '</div>');
      $('html, body').animate({
        scrollTop: $('#new_person_box').offset().top
      }, 1000);
    }
  });
</script>

app/views/people/_form_page_title.erb
<h3>Search/Add Person</h3>

app/views/people/_onkeyup_search.erb
<% if current_user and current_user.has_access?(PERM_RW_PERSON) %>
App.People.updatePersonSearch(this, false, true);
<% else %>
App.People.updatePersonSearch(this);
<% end %>

app/views/people/_search_results.html.erb
<% if @people.length > 0 %>
    <div id="results-list" class="results">
      <ul data-dropdown-content>
        <% @people.each_with_index do |person, index|
          rowclass = 'oddrow '
          rowclass = 'evenrow ' if index % 2 == 0
          rowclass += 'last-element' if index == @people.length - 1
        %>
            <li class="<%= rowclass %>" onclick="window.location = '<%= url_for person_path(person) %>';">
              <div><%= deduplicate_person(person) %></div>
            </li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/people/edit.html.erb
<div class="row">
	<div class="small-12 medium-9 large-8 columns small-centered">
		<h3>Edit Person</h3>
		<%= render 'form' %>
    </div>
</div>

app/views/people/index.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <div class="searchbox">
      <div id="searcharea">
        <%= form_tag '/people/new' do %>
            <%= render 'form_page_title' %>

            <div class="row">
              <div class="large-12 columns">
                <input id="search" autocomplete="off" onkeyup="<%= render 'onkeyup_search' %>"
                       type="text"
                       size="30"
                       name="search"
                       placeholder="Firstname Lastname"
                       value="<%= @search_string %>"/>
              </div>
            </div>
            </div>
            <div class="row">
              <div class="large-12 columns">
                <div>
                  <%= submit_tag nil, class: 'small hide', id: 'newperson' %>
                </div>
              </div>
              <div id="results" class="large-12 columns">
                <%= render "people/search_results" %>
              </div>
            </div>
            <% end %>
        </div>
  </div>
</div>

app/views/people/new.html.erb
<div class="row">
	<div class="small-12 medium-9 large-8 columns small-centered">
  		<h3>Create New Person</h3>
  		<%= render 'form' %>
    </div>
</div>

app/views/people/show.html.erb
<br/>
<div class="row">
  <div class="large-8 radius large-centered columns grey">
    <div class="row title dark-grey">
      <div class="large-12 columns">
        <p><%= @person.fullname %></p>
      </div>
    </div>
    <div class="row">
      <div class="small-12 columns">
        <p>
          <strong>Address</strong><br/>
          <% if @person.household and @person.household.address %>
              <%= @person.household.address.line1 %><br/>
              <% if !@person.household.address.line2.empty? %>
                  <%= @person.household.address.line2 %><br/>
              <% end %>
              <%= @person.household.address.city_state_zip %>
          <% else %>
              <i>No address on file</i>
          <% end %>
        </p>
      </div>
      <div class="small-12 columns">
        <p>
          <strong>Phone</strong><br/>
          <% if @person.phone %>
            <%=  number_to_phone(@person.phone, area_code: true, extension: @person.phone_ext) %>
          <% else %>
              <i>No phone on file</i>
          <% end %>
        </p>
      </div>
      <div class="small-12 columns">
        <p>
          <strong>Email</strong><br/>
          <%= @person.email %>
          <% if @person.user and @person.user.has_pending_email_change? %><i> (Pending change to: <%= @person.user.pending_email %>)</i>
          <% end %>
        </p>
      </div>
      <% if @person.user %>
          <div class="small-12 columns">
            <p>
              <strong>User Roles</strong><br/>
              <% if @person.user and @person.user.roles %>
                  <% @person.user.roles.each do |role| %>
                      <% if @person.user.roles.include?(role) %>
                          &#10003; <%= role.name %>
                      <% else %>
                          <span class="grey">&#10007; <%= role.name %></span>
                      <% end %>
                      <br/>
                  <% end %>
              <% else %>
                  User has no roles.
              <% end %>
            </p>
          </div>
      <% end %>

      <% if @person.notes %>
          <div class="small-12 columns">
            <p>
              <strong>Notes</strong><br/>
              <% @person.notes.each do |n| %>
                <span style="font-style:italic"><%= NoteType.find(n.note_type_id).name %>: </span>
                <%= n.note %><br/>
              <% end %>
            </p>
          </div>
      <% end %>

    </div>
  </div>
</div>

<div class="row space-above">
  <div class="large-8 radius large-centered columns yellow">
    <div class="row title">
      <div class="large-12 columns">
        <p>Household Information</p>
      </div>
    </div>
    <div class="row">
      <% if @person.household %>
          <%= render :partial => '/household/show' %>
      <% else %>
          <div class="large-12 columns"><i>No household information</i></div>
      <% end %>
    </div>
  </div>
</div>


<div class="row space-above collapse">
  <div class="large-8 radius large-centered columns">
    <%= link_to('Edit', edit_person_path(@person), :class => 'button medium') if current_user and current_user.has_access?(PERM_RW_PERSON) %>

    <%= link_to 'New Visit', new_visit_path(:person_id => @person, :host_id => current_user.person.id), :class => 'button medium' %>
  </div>
</div>