config/routes.rb
Thirtyone::Application.routes.draw do

  resources :local_resource_categories

  resources :local_resources do
    collection do
      get :search
    end
  end

  resources :visits

  resources :user_roles

  devise_for :users

  resources :calendar, only: [:index]

  scope 'inventory' do
    resources :items, as: 'inventory_items', controller: 'inventory_items'
    resources :orders, controller: 'inventory_orders'

    resources :inventory_stock_records
  end

  root  'static_pages#index'

  resources :user, controller: 'users', only: [:index, :edit, :update]
  resources :role, as: "roles", controller: "roles", via: :all

  match '/adminsetup', :controller => 'adminsetup', :action => 'setup', :via => 'get'
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_new', via: :get
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_create', via: :post

  resources :event, as: 'events', controller: 'event', via: :all

  resources :households, controller: 'household' do
    collection do
      get :search
      get :select
      get '/:id/merge'            => 'household#merge_select',        as: 'merge_select'
      get '/:id/merge/:merge_id'  => 'household#merge_select_fields', as: 'merge_select_fields'
      patch ':id/merge/:merge_id' => 'household#merge',               as: 'merge'
    end
    resources :addresses
  end

  resources :event, as: "events", controller: "event", via: :all

  resources :work_schedule, as: "work_schedules", controller: "work_schedule", via: :all

  resources :people do
    collection do
      get 'search'
    end
  end

  delete '/user/:id/email_change'     => 'users#cancel_pending_email_change', as: 'cancel_pending_email_change'
  post '/user/:id/email_confirmation' => 'users#send_confirmation_email', as: 'send_confirmation_email'
  get '/user/:id/email_confirmation'  => 'users#confirm_email_change', as: 'confirm_email_change'

  match '/people/new', :controller => 'people', :action => 'new', via: :post

end

app/models/household.rb
# == Schema Information
#
# Table name: households
#
#  id         :integer          not null, primary key
#  name       :string
#  person_id  :integer
#  created_at :datetime
#  updated_at :datetime
#  address_id :integer
#

class Household < ActiveRecord::Base
  belongs_to :person, dependent: :destroy
  belongs_to :address
  has_and_belongs_to_many :notes, join_table: 'notes_households'
  alias_method :head, :person
  alias_method :head=, :person=
  has_many :members, class_name: 'Person', foreign_key: 'household_id'
  has_many :household_limits
  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :household_limits, allow_destroy: true
  validates_associated :address

  acts_as_paranoid

  def summary
    s = "#{person.formal_name}"
    s << " - #{self.address.oneline_summary}" if self.address
  end

  def name
    person.lastname
  end

  #alias_method :people, :persons
  #alias_method :members, :persons

end

app/controllers/household_controller.rb
require 'uri'
class HouseholdController < ApplicationController
  before_action :authenticate_user!
  before_action :set_household, only: [:show, :edit, :update, :destroy, :merge_select, :merge_select_fields, :merge]
  before_action :set_merge_household, only: [:merge, :merge_select_fields]
  before_action :authorize_household

  def index
    @households = Household.all
    if params[:ajax]
      render partial: 'search'
    end
  end

  def create
    @household = Household.new
    @household.address = Address.new(address_params)

    respond_to do |format|
      if @household.valid? and @household.errors.empty?
        if params[:redirect_to_url]
          format.html {redirect_to params[:redirect_to_url]}
        else
          household_data = {"address" => {"line1"    => @household.address.line1,
                                          "line2"    => @household.address.line2,
                                          "city"     => @household.address.city,
                                          "state_id" => @household.address.state_id,
                                          "zip"      => @household.address.zip}}

          format.html { redirect_to "#{new_person_url}?household_data=#{URI.encode(JSON.dump(household_data))}", notice: 'Please complete this form to add a head of household' }
          format.json { render action: 'show', status: :created, location: @household }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @household.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html {
        if params[:ajax]
          render :partial => 'show', person_select: true
        else
          render 'show'
        end
      }
      #format.json { render action: 'show.json' }
    end
  end

  def edit
    respond_to do |format|
      format.html {
        if params[:ajax]
          render :partial => 'edit'
        else
          render 'edit'
        end
      }
    end
  end

  def update
    @household.address.update(address_params)
    @household.update(household_limit_params)

    respond_to do |format|
      format.html { redirect_to @household, notice: 'Household was successfully updated.' }
    end
  end

  # DELETE /household/1
  # DELETE /household/1.json
  def destroy
    @household.destroy
    respond_to do |format|
      format.html { redirect_to households_url, notice: 'Household was deleted.' }
      format.json { head :no_content }
    end
  end

  def new
    @household = Household.new
    @household.address = Address.new
    @household.address.state = State.most_used_state
    @all_states = State.all
    respond_to do |format|
      format.html {
        if params[:ajax]
          render :partial => 'new'
        else
          render 'new'
        end
      }
      #format.json { render action: 'new.json' }
    end
  end

  # Used for selecting a household and associating it with a person
  def select
    @households = Household.all
    if params[:ajax]
      render partial: 'select'
    end
  end

  def merge_select
    @households = Household.where('id != ?', @household.id).all

    render 'merge', locals: {action: 'merge_household'}
  end

  def merge_select_fields
  end

  def merge
    success = false
    @household.transaction do
      @household.address_id = params[:address_id]
      @household.person_id = params[:head_id]
      members = Person.where(id: params[:member_ids])
      if not params[:member_ids].include?(params[:head_id])
        @household.errors.add(:person, 'You cannot delete the same user you have selected as the head of household')
        raise ActiveRecord::Rollback
      end
      @household.members = members
      success = @household.save
      @merge_household.delete
    end
    if success
      respond_to do |format|
        format.html { redirect_to @household, notice: 'Household was successfully merged.' }
      end
    else
      # Reset household and merge_household back to original state
      # Without this the @household attribute would show a partially
      # merged state, while @merge_household would show it's original state
      #
      # The goal is to never hit this server side error, but have Javascript that
      # prevents all errors.  This page is completely checkbox and radio button
      # operated.  So javascript should be able to catch most potential errors
      # ahead of time.
      errors = @household.errors
      set_household
      set_merge_household

      # Need to set the errors on @household for display purposes
      errors.each do |attr, msg|
        @household.errors.add(attr, msg)
      end
      respond_to do |format|
        format.html {
          render 'merge_select_fields'
        }
      end
    end
  end

  def search
    wild_card_query_fields = %w(people.firstname people.lastname)
    sql_params = []
    sql_where = ''

    if (params[:search])

      rowlimit = params[:rowlimit] || 10
      search_keys = JSON.parse(params[:search]).to_a

      wild_card_query_fields.each do |field|
        search_keys.each do |key|
          sql_where += ' OR ' if sql_where != ''
          sql_where += "#{field} LIKE ?"
          sql_params.push("#{key}%")
        end
      end

      @households = Household.joins(:person).where(sql_where, *sql_params).order('people.lastname').first(rowlimit.to_i)

    else
      @households = Household.all
    end
    #@people = Person.where("firstname LIKE ? #{sql_conditional} lastname LIKE ?", firstname_key, lastname_key).first(rowlimit.to_i)
    @new_household = Household.new
    respond_to do |format|
      format.html {
        if params[:ajax]
          render :partial => 'search_results'
        else
          render action: 'index'
        end
      }
      format.json { render action: 'index.json' }
    end
  end

  private

  def set_household
    @household = Household.find(params[:id])
    @all_states = State.all
  end

  def set_merge_household
    @merge_household = Household.find(params[:merge_id])
  end

  def household_params
    params.require(:household).permit(:address, :household_limit => [])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def address_params
    params.require(:address).permit(:line1, :line2, :city, :state, :zip, :state_id)
  end

  def household_limit_params
    params.require(:household).permit(household_limits_attributes:[:inventory_item_id, :quantity, :id, :_destroy])
  end

  def authorize_household
    @household ? (authorize @household) : (authorize :household)
  end
end

app/helpers/household_helper.rb
module HouseholdHelper
end

app/views/household/_household_limit_fields.html.erb
<tr class="fields">
    <td>
      <div class="small-6 columns">
        <label>Iventory Item</label>
      </div>
      <div class="small-6 columns">
        <label>Quantity Override</label>
      </div>
      <div class="small-6 columns">
        <%= f.collection_select :inventory_item_id, InventoryItem.all, :id, :name %>
      </div>
      <div class="small-6 columns">
        <%= f.text_field :quantity %>
      </div>
    </td>
    <td><%= link_to_remove_fields "Remove", f %></td>
</tr>

app/views/household/_merge_household_address.html.erb
<div class="row">
  <div class="small-12 columns">
    <label><h5>Address</h5></label>
  </div>
</div>
<div class="row">
  <div class="small-1 columns">
    <input type="radio" name="address_id" value="<%= household.address_id %>" <% if defined?(default) %>checked="checked"<% end %>/>
  </div>
  <div class="small-11 columns">
    <% if household.address %>
        <%= household.address.line1 %><br />
        <% if !household.address.line2.empty? %><%= household.address.line2 %><br /><% end %>
        <%= household.address.city_state_zip %>
    <%else%>
        None on file
    <% end %>
  </div>
</div>

app/views/household/_merge_household_members.html.erb
<div class="row">
  <div class="small-12 columns">
    <label><h5>Members to Keep</h5></label>
  </div>
</div>

<% household.members.each do |person| %>
    <div class="row member-wrap">
      <div class="small-1 columns">
        <input name="member_ids[]" type="checkbox" checked="checked" onchange="App.Household.mergeMemberChecked(this);" value="<%= person.id %>" />
      </div>
      <div class="small-11 columns member-name">
        <%= person.fullname %>
        <span class="red-text deleted hide">(Will be Deleted)</span>
      </div>
    </div>
<% end %>

app/views/household/_merge_household_name.html.erb
<div class="row">
  <div class="small-12 columns">
    <label><h5>Household Name</h5></label>
    <span><%= household.name %></span>
  </div>
</div>

app/views/household/_new.html.erb
<%= fields_for @household do |h| %>

    <% if @household.errors.any? %>
        <div class="small-12 columns">
          <div id="error_explanation">
            <h2><%= pluralize(@household.errors.count, "error") %> prohibited this household from being saved:</h2>

            <ul>
              <% @household.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

      <div class="small-12 columns">
        <label for="household_name">Household Name</label>
        <input disabled="disabled" type="text" id="household_summary" value="" />
      </div>
      <div class="small-12 columns">
        <%= fields_for :address, @household.address do |a| %>
            <div class="field">
              <label for="household_address_line1">Address Line 1</label>
              <%= a.text_field :line1 %>
            </div>
            <div class="field">
              <label for="household_address_line2">Address Line 2</label>
              <%= a.text_field :line2 %>
            </div>
            <div class="field">
              <label for="household_address_city">City</label>
              <%= a.text_field :city %>
            </div>
            <div class="field">
              <label for="household_address_state">State</label>
              <%= a.collection_select :state_id, State.all, :id, :name %>
            </div>
            <div class="field">
              <label for="household_address_zip">Zipcode</label>
              <%= a.text_field :zip %>
            </div>
        <% end %>
      </div>
<% end %>

app/views/household/_search.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <div class="searchbox">
      <div id="searcharea">
        <h3>Search/Add Household</h3>
        <div class="row">
          <div class="large-8 columns">
            <input id="search" onkeyup="App.Household.updateHouseholdSearch(this);" type="text" size="30" name="search" placeholder="Name, Address, etc" value="" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= link_to "New Household", {action: "new"}, class: "medium button" %>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <% if defined? action %>
            <%= render 'search_results', action: action %>
          <% else %>
            <%= render 'search_results' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/household/_select.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <div class="searchbox">
      <div id="searcharea">
        <h3>Search/Add Household</h3>
        <div class="row">
          <div class="large-8 columns">
            <input id="search" onkeyup="App.Household.updateHouseholdSearch(this);" type="text" size="30" name="search" placeholder="Name, Address, etc" value="" />
          </div>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <button type="button" onclick="App.Household.newHouseholdAjax('<%= new_household_url %>');" class="button medium">New Household</button>
        </div>
      </div>
      <div class="row">
        <div class="large-12 columns">
          <%= render 'search_results', person_select: true %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/household/_show.html.erb
<div class="row">
<div class="small-12 columns">
  <div class="existing_household">
        <strong>Name</strong><br />
        <%= @household.name %><br /><br />
        <strong>Members</strong><br />
        <%= @household.members.map {|person| person.formal_name}.join('; ') %><br /><br />
        <strong>Address</strong><br />
        <% if @household.address %>
            <%= @household.address.line1 %><br />
            <% if !@household.address.line2.empty? %><%= @household.address.line2 %><br /><% end %>
            <%= @household.address.city_state_zip %>
        <%else%>
            None on file
        <% end %>
    <input type="hidden" name="person[household_id]" value="<%= @household.id %>" />
  </div>
</div>
</div>

app/views/household/edit.html.erb
<%= form_for(@household) do |form| %>

  <div style="margin-top:20px;" class="row">
    <div class="small-12 medium-8 large-8 columns small-centered">
      <%= render :partial => 'household/new', :locals => {:f => form} %>
    </div>
  </div>

    <div class="row">
      <div class="small-12 medium-8 large-8 columns small-centered">
        <table id="household_limits_table" class="layout-wrapper">
            <%= form.fields_for :household_limits do |builder| %>
                <%= render 'household_limit_fields', :f => builder %>
            <% end %>
        </table>
      </div>
    </div>

    <div class="row">
      <div class="small-12 medium-8 large-8 columns small-centered">
        <div class="small-12 columns">
          <p><%= link_to_add_fields "Add Inventory Override", form, :household_limits, "#household_limits_table" %></p>
        </div>
      </div>
    </div>

  <div class="row">
    <div class="large-8 small-12 columns small-centered">
      <div class="small-12 columns">
        <h3>Members</h3>
        <% @household.members.each do |member| %>
            <li><%= link_to member.formal_name, edit_person_path(member, :redirect_to_url => edit_household_path(@household)) %></li>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row space-above">
    <div class="large-8 columns small-12 small-centered clearfix">
      <div class="small-12 columns">
        <%= form.submit 'Save', :class => 'medium button left' %>
        <%= link_to("New Person", new_person_path(:household_id => @household.id, :redirect_to_url => edit_household_path(@household)), :class => 'button medium right') %>
      </div>
    </div>
  </div>

<% end %>

app/views/household/index.html.erb
<%= render 'search' %>

app/views/household/merge.html.erb
<%= render 'search', action: 'merge_household' %>

app/views/household/merge_select_fields.html.erb
<div class="row space-bottom">
  <div class="small-12 columns">
    <h1>Merge Households</h1>
    <span>Select the information from the household you would like to preserve.</span>
  </div>
</div>
 <%= form_for(@household, url: merge_households_path) do |f| %>

    <div class="row space-bottom">
      <div class="small-12 columns">
        <% if @household.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@household.errors.count, "error") %> prohibited these households from being merged:</h2>
            <ul>
              <% @household.errors.each do |attr, msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row space-bottom">
      <div class="small-6 columns">
        <%= render 'merge_household_name', household: @household %>
      </div>
      <div class="small-6 columns">
        <%= render 'merge_household_name', household: @merge_household %>
      </div>
    </div>
    <div class="row space-bottom">
      <div class="small-6 columns">
        <%= render 'merge_household_address', household: @household, default: true %>
      </div>
      <div class="small-6 columns">
        <%= render 'merge_household_address', household: @merge_household %>
      </div>
    </div>


    <div class="row space-bottom">
      <div class="small-6 columns">
        <%= render 'merge_household_members', household: @household %>
      </div>
      <div class="small-6 columns">
        <%= render 'merge_household_members', household: @merge_household %>
      </div>
    </div>


    <div class="row space-bottom">
      <div class="small-6 columns">
        <%= render 'merge_select_head_of_household', household: @household, default: true %>
      </div>
      <div class="small-6 columns">
        <%= render 'merge_select_head_of_household', household: @merge_household %>
      </div>
    </div>

    <div class="row">
      <div class="small-12 columns">
        <input type="submit" class="medium button" value="Merge" />
      </div>
    </div>
  <% end %>
</div>

app/views/household/new.html.erb
<div class="row">
  <div class="large-8 small-12 columns small-centered">
    <h1>Create a Household</h1>
  </div>
    <%= form_for(@household) do |form| %>
      <div clas="large-2 columns"></div>
      <div class="large-8 small-12 columns small-centered">
      <%= render :partial => 'household/new', :locals => {:f => form} %>
      </div>
      <div clas="large-2 columns"></div>
      <div clas="large-2 columns"></div>
      <div class="large-8 small-12 columns small-centered">
         <div class="small-12 columns">
           <%= form.submit 'Create Household', class: 'medium button' %>
         </div>
      </div>
      <div clas="large-2 columns"></div>
<% end %>
</div>

app/views/household/show.html.erb
<div class="row space-above">
  <div class="large-10 large-offset-2 small-12 columns">
    <h1>The <%= @household.name %> Household</h1>
  </div>
</div>
<div class="row">
  <div class="large-8 small-12 columns small-centered">
      <%= render 'show' %>
    </div>
</div>
<div class="row space-above">
  <div class="large-6 small-12 large-offset-2 columns">
    <%= link_to('Edit', edit_household_path(@household), :class => 'button medium') if current_user and current_user.has_access?(PERM_RW_PERSON) %>
    <%= link_to('Delete', @household, :class => 'button medium', method: :delete, data: { confirm: "This will delete the household and ALL members of the household.\n\nAre you sure?" }) if current_user and current_user.has_access?(PERM_RW_PERSON) %>
  </div>
  <div class="large-4 large-pull-2 columns text-right">
    <%= link_to('Merge Household', merge_select_households_path(@household), :class => 'button medium') if current_user and current_user.has_access?(PERM_RW_PERSON) %>
  </div>
  <div id="selectHouseholdModal" class="reveal-modal" data-reveal>
    <a class="close-reveal-modal">&#215;</a>
  </div>
</div>