config/routes.rb
Thirtyone::Application.routes.draw do

  resources :local_resource_categories

  resources :local_resources do
    collection do
      get :search
    end
  end

  resources :visits

  resources :user_roles

  devise_for :users

  resources :calendar, only: [:index]

  scope 'inventory' do
    resources :items, as: 'inventory_items', controller: 'inventory_items'
    resources :orders, controller: 'inventory_orders'

    resources :inventory_stock_records
  end

  root  'static_pages#index'

  resources :user, controller: 'users', only: [:index, :edit, :update]
  resources :role, as: "roles", controller: "roles", via: :all

  match '/adminsetup', :controller => 'adminsetup', :action => 'setup', :via => 'get'
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_new', via: :get
  match '/roles/bulk', :controller => 'roles', :action => 'bulk_assign_create', via: :post

  resources :event, as: 'events', controller: 'event', via: :all

  resources :households, controller: 'household' do
    collection do
      get :search
      get :select
      get '/:id/merge'            => 'household#merge_select',        as: 'merge_select'
      get '/:id/merge/:merge_id'  => 'household#merge_select_fields', as: 'merge_select_fields'
      patch ':id/merge/:merge_id' => 'household#merge',               as: 'merge'
    end
    resources :addresses
  end

  resources :event, as: "events", controller: "event", via: :all

  resources :work_schedule, as: "work_schedules", controller: "work_schedule", via: :all

  resources :people do
    collection do
      get 'search'
    end
  end

  delete '/user/:id/email_change'     => 'users#cancel_pending_email_change', as: 'cancel_pending_email_change'
  post '/user/:id/email_confirmation' => 'users#send_confirmation_email', as: 'send_confirmation_email'
  get '/user/:id/email_confirmation'  => 'users#confirm_email_change', as: 'confirm_email_change'

  match '/people/new', :controller => 'people', :action => 'new', via: :post

end

app/models/local_resource.rb
# == Schema Information
#
# Table name: local_resources
#
#  id            :integer          not null, primary key
#  business_name :string
#  phone         :string
#  phone_ext     :string
#  email         :string
#  url           :string
#  address_id    :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class LocalResource < ActiveRecord::Base
  include PhoneMethod

  has_and_belongs_to_many :local_resource_categories
  validates_presence_of :local_resource_categories
  validates_presence_of :business_name
  validates_associated :address
  belongs_to :address
  before_save :strip_phone_number

  accepts_nested_attributes_for :address

  def strip_phone_number
    self.phone = self.strip_phone(self.phone)
    self.phone_ext = self.strip_phone_ext(self.phone_ext)
  end

end

app/controllers/local_resources_controller.rb
class LocalResourcesController < ApplicationController
  before_action :set_local_resource, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :authorize_local_resource

  # GET /local_resources
  # GET /local_resources.json
  def index
    @local_resources = LocalResource.all
    @local_resource_categories = LocalResourceCategory.all
  end

  # GET /local_resources/1
  # GET /local_resources/1.json
  def show
  end

  def search
    @local_resources, @local_resource_categories = LocalResourceSearch.search(params)
    respond_to do |format|
      format.html {
         render partial: 'search_results'
      }
      format.json { render action: 'index.json' }
    end
  end

  # GET /local_resources/new
  def new
    @local_resource = LocalResource.new
    @address = Address.new
  end

  # GET /local_resources/1/edit
  def edit
    @state_id = @local_resource.address.state_id
    @local_resource_categories = @local_resource.local_resource_categories.map(&:id)
  end

  # POST /local_resources
  # POST /local_resources.json
  def create
    @local_resource = LocalResource.new(local_resource_params)

    # Make the address nil if the user didn't enter anything. Otherwise, set the state.
    if params[:local_resource][:address_attributes][:line1].blank?
      @local_resource.address = nil
    else
      update_state
    end

    update_local_resource_categories

    respond_to do |format|
      if @local_resource.save
        format.html { redirect_to @local_resource, notice: 'Local resource was successfully created.' }
        format.json { render action: 'show', status: :created, location: @local_resource }
      else
        # Set the address if we set it to nil above
        @address = Address.new if @address.nil?
        format.html { render action: 'new' }
        format.json { render json: @local_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /local_resources/1
  # PATCH/PUT /local_resources/1.json
  def update
    respond_to do |format|
      if @local_resource.update(local_resource_params)
        update_state
        update_local_resource_categories
        format.html { redirect_to @local_resource, notice: 'Local resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @local_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /local_resources/1
  # DELETE /local_resources/1.json
  def destroy
    @local_resource.destroy
    respond_to do |format|
      format.html { redirect_to local_resources_url }
      format.json { head :no_content }
    end
  end

  private
    def update_state
      @local_resource.address.state = State.find(params[:local_resource][:address_attributes][:state])
    end

    def update_local_resource_categories
      @local_resource.local_resource_categories = []

      params[:local_resource][:local_resource_categories].each do |local_resource_category_id|
        next if local_resource_category_id.blank?
        @local_resource_category = LocalResourceCategory.find(local_resource_category_id)
        @local_resource.local_resource_categories << @local_resource_category
        @local_resource.save
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_local_resource
      @local_resource = LocalResource.find_by(id: params[:id])
      redirect_to local_resources_url unless @local_resource
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def local_resource_params
      params.require(:local_resource).permit(:contact_name, :business_name, :phone, :phone_ext, :email, :url,
                                             address_attributes: [:line1, :line2, :city, :zip])
    end

    def authorize_local_resource
      authorize :local_resource
    end
end

app/helpers/local_resources_helper.rb
module LocalResourcesHelper
end

app/views/local_resources/_form.html.erb
<%= form_for(@local_resource) do |f| %>
    <% if @local_resource.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@local_resource.errors.count, 'error') %> prohibited this local_resource from being
            saved:</h2>

          <ul>
            <% @local_resource.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div style="color: red;">* denotes required field</div>
    <div class="field">
      <%= f.label :business_name, class: :required %><br>
      <%= f.text_field :business_name %>
    </div>
    <div class="phone_field">
      <div class="phone_left">
        <span><%= f.label :phone %></span>
        <span><%= f.text_field :phone %></span>
      </div>
      <div class="phone_right">
        <span><%= f.label :phone_ext %></span>
        <span><%= f.text_field :phone_ext %></span>
      </div>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <%= f.label :address %><br>
    <%= f.fields_for :address, @address do |a| %>
        <div class="field">
          <%= a.label :line1, 'Address Line 1' %>
          <%= a.text_field :line1 %>
        </div>
        <div class="field">
         <%= a.label :line2, 'Address Line 2' %>
          <%= a.text_field :line2 %>
        </div>
        <div class="field">
          <%= a.label :city %>
          <%= a.text_field :city %>
        </div>
        <div class="field">
          <%= a.label :state %>
          <%= a.collection_select :state, State.all, :id, :name, {:selected => @state_id } %>
        </div>
        <div class="field">
          <%= a.label :zip, 'Zipcode' %>
          <%= a.text_field :zip %>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :categories, class: :required %><br>
      <%= f.collection_check_boxes :local_resource_categories, LocalResourceCategory.all, :id, :name, {:checked => @local_resource_categories} %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/local_resources/_search_results.html.erb
<% @local_resource_categories.each do |local_resource_category| %>
    <div class="row">
      <div class="large-8 large-centered small-12 columns expand">
        <div class="title dark-grey radius-top" style="padding-left:15px;">
          <p><span class="toggle">▼</span> <%= local_resource_category.name %></p>
        </div>
      </div>
      <div class="large-8 large-push-2 columns small-12 content radius-bottom end">
        <div class="grey" style="padding-left:15px;">
              <% @local_resources.includes(:local_resource_categories)
                                 .where(local_resource_categories_resources: {local_resource_category_id: [local_resource_category.id]})
                                 .each do |local_resource| %>
              <strong><%= local_resource.business_name %></strong><br/>
              <% unless local_resource.phone.blank? %>
                  <span class="ui-icon ui-icon-contact icon"></span><%= number_to_phone(local_resource.phone, area_code: true, extension: local_resource.phone_ext) %><br/>
              <% end %>
              <% unless local_resource.address.blank? %>
                  <span class="ui-icon ui-icon-pin-s icon"></span><%= link_to local_resource.address.oneline_summary,
                                                                              "https://www.google.com/maps/place/#{local_resource.address.oneline_summary}" %>
                  <br/>
              <% end %>
              <% unless local_resource.email.blank? %>
                  <span class="ui-icon ui-icon-mail-closed icon"></span><%= mail_to local_resource.email %><br/>
              <% end %>
              <% unless local_resource.url.blank? %>
                  <span class="ui-icon ui-icon-home icon"></span><%= link_to 'Website', local_resource.url, :target => '_blank' %><br/>
              <% end %>
              <%= link_to('Edit', edit_local_resource_path(local_resource)) if current_user.has_access?(PERM_RW_RESOURCE) %> |
              <%= link_to('Delete', local_resource, :method => :delete, :data => {:confirm => 'Are you sure?'}) if current_user.has_access?(PERM_RW_RESOURCE) %><br/>
              <% if not local_resource.equal? local_resource_category.local_resources.last %>
                  <br/>
              <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <br/>
<% end %>

app/views/local_resources/edit.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <h1>Editing Local Resource</h1>

    <%= render 'form' %>

    <%= link_to 'Show', @local_resource %> |
    <%= link_to 'Back', local_resources_path %>
  </div>
</div>

app/views/local_resources/index.html.erb
<br/>
<div class="row large-centered space-bottom">
  <div class="large-8 large-centered columns">
    <a class="button medium" href="<%= new_local_resource_path %>">New Local Resource</a>
  </div>
</div>
<%= form_tag search_local_resources_path do %>
  <div class="row space-bottom">
    <div class="large-8 large-centered columns small=12">
      <fieldset>
        <legend>Filter</legend>
        <div class="row">
          <div class="small-12 columns">
            <input id="search" autocomplete="off" onkeyup="App.Local_Resources.updateLocalResourceSearch(this);"
                   type="text"
                   size="30"
                   name="search[term]"
                   placeholder="Business Name"
                   value="<%= @search_string %>"/>
          </div>
        </div>
        <div class="row">
          <div class="small-12 columns">
            <%= collection_check_boxes :search, :local_resource_categories, LocalResourceCategory.all, :id, :name, {}, {checked: "checked", onchange: "App.Local_Resources.updateLocalResourceSearch(this);"} %>
          </div>
        </div>
      </fieldset>
    </div>
  </div>
<% end %>
<div id="results" class="large-12 columns">
  <%= render "local_resources/search_results" %>
</div>

app/views/local_resources/new.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <h1>New Local Resource</h1>

    <%= render 'form' %>

    <%= link_to 'Back', local_resources_path %>
  </div>
</div>

app/views/local_resources/show.html.erb
<div style="margin-top:20px;" class="row">
  <div class="small-12 medium-9 large-8 columns small-centered">
    <p id="notice"><%= notice %></p>

    <p>
      <strong>Business name:</strong>
      <%= @local_resource.business_name %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= number_to_phone(@local_resource.phone, area_code: true, extension: @local_resource.phone_ext)%>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @local_resource.email %>
    </p>

    <p>
      <strong>Url:</strong>
      <%= @local_resource.url %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @local_resource.address.blank? ? '' : @local_resource.address.oneline_summary %>
    </p>

    <%= link_to 'Edit', edit_local_resource_path(@local_resource) %> |
    <%= link_to 'Back', local_resources_path %>
  </div>
</div>